-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender;

--or--
SELECT 
  gender,
  SUM(purchase_amount) AS total_revenue,
  ROUND(100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER (), 2) AS revenue_share_pct
FROM customer
GROUP BY gender;


select * from customer

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

with cte as (
select customer_id , sum(purchase_amount) as total_amount
from customer 
where discount_applied = 'Yes'
group by customer_id
)
select c.customer_id,c.total_amount
from cte as c
join customer as j
on c.customer_id = j.customer_id
where c.total_amount > (select round(avg(purchase_amount))as avg_purchase_amount from customer);

--Q3. Which are the top 5 products with the highest average review rating?

select * from customer;

select item_purchased, round(avg(review_rating):: numeric,2) as avg_review_rating from customer
group by item_purchased
order by avg_review_rating desc
limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express shipping.

select * from customer


select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from customer
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend 
-- and total revenue between subscribers and non-subscribers.

select * from customer;

select subscription_status ,count(distinct customer_id) as total_customer,round(avg(purchase_amount),2) as avg_purchase_amount,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select * from customer;

SELECT
    item_purchased,
    ROUND(100.0 * sum(case when discount_applied = 'Yes' Then 1 else 0 end ) / count(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the count of each segment.
select * from customer

SELECT 
COUNT(DISTINCT customer_id) AS total_customers,
  CASE
    WHEN previous_purchases < 10 THEN 'New'
    WHEN previous_purchases < 30 THEN 'Returning'
    ELSE 'Loyal'
  END AS customer_segment
FROM customer
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

select * from customer;

with cte as(
select item_purchased , category,count(customer_id) as total_order,
row_number()over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by item_purchased,category
)
select item_rank, category,item_purchased,total_order from cte 
where item_rank <=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select * from customer

select count(distinct customer_id) as total_customer , subscription_status
from customer
where previous_purchases >5 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group?

select * from customer;

select age_group , sum(purchase_amount) as total_amount
from customer
group by age_group
order by total_amount desc;











